name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    concurrency:
      group: bot-run
      cancel-in-progress: false  # Keep this false for fastest restarts

    runs-on: ubuntu-latest
    timeout-minutes: 355  # Just under 6-hour GitHub limit

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
    
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Set Executable Permissions
        run: |
          chmod +x ./engines/stockfish

      - name: Run Bot
        run: |
          echo "Starting bot..."
          python3 -u user_interface.py --matchmaking &
          PID=$!
          
          # Auto-exit after 350 minutes (so restart runs without overlap)
          ( sleep 21000 && echo "Time up. Killing bot..." && kill -SIGTERM $PID ) &
          
          wait $PID
          echo "Bot ended cleanly."

      - name: 🔁 Self-Restart (Fire-and-Forget)
        if: always()
        run: gh workflow run bot.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
