name: Lichess Mass Challenge

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  run-challenges:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4️⃣ Run the mass challenge script
      - name: Send challenges to Lichess bot
        env:
          TOKEN: ${{ secrets.TOKEN }}  # Secure API token from repo secrets
        run: |
          python -u One.py
